modLoader="javafml" #mandatory

loaderVersion="[28,)" #mandatory (28 is current forge version)

#issueTrackerURL="N/A" 
#None available ^^

[[mods]] #mandatory

modId="hbsutilitymod" #mandatory

version="0.3.0" 

displayName="Heart-Broken Souls Utility Mod"

#updateJSONURL="N/A"
#None available ^^

#displayURL="N/A"
#None available ^^

#logoFile="N/A"
#None available ^^

credits="I'd like to thank Harry Talks on Youtube for being my main guide to help me get started on creating mods. His tutorials were pretty helpful for me, and allowed me to even get started."
authors="ANARCH1ST_S0ULS"
description='''
Random items, tools, blocks and crafting recipes I thought would be interesting.
'''

[[dependencies."hbsutilitymod"]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28.2.0,)" #mandatory
    ordering="NONE"
    side="BOTH"


[[dependencies."hbsutilitymod"]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"